import type { MysteryBookCandidate } from "../types/mystery";

// Placeholder catalog standing in for the curated Mystery Book catalog described in
// PRD Section 13.2 (Signal D) — real sourcing/ownership is still Open Question #11.
export const MYSTERY_CATALOG: MysteryBookCandidate[] = [
  {
    id: "night-circus",
    title: "The Night Circus",
    author: "Erin Morgenstern",
    genres: ["fantasy", "romance"],
    moodProfile: { magical: 0.9, escapist: 0.9, emotional: 0.6, intense: 0.2, thoughtProvoking: 0.7 },
    approxPages: 400,
    popularity: 0.8,
  },
  {
    id: "silent-patient",
    title: "The Silent Patient",
    author: "Alex Michaelides",
    genres: ["mysteryThriller"],
    moodProfile: { intense: 0.9, mysterious: 0.9, emotional: 0.4, thoughtProvoking: 0.5 },
    approxPages: 340,
    popularity: 0.85,
  },
  {
    id: "project-hail-mary",
    title: "Project Hail Mary",
    author: "Andy Weir",
    genres: ["scienceFiction", "adventure"],
    moodProfile: { escapist: 0.7, lightFun: 0.6, thoughtProvoking: 0.7, intense: 0.5 },
    approxPages: 480,
    popularity: 0.9,
  },
  {
    id: "seven-husbands",
    title: "The Seven Husbands of Evelyn Hugo",
    author: "Taylor Jenkins Reid",
    genres: ["romance", "literaryFiction"],
    moodProfile: { emotional: 0.9, escapist: 0.5, cozy: 0.3, intense: 0.4 },
    approxPages: 390,
    popularity: 0.92,
  },
  {
    id: "house-in-the-cerulean-sea",
    title: "The House in the Cerulean Sea",
    author: "TJ Klune",
    genres: ["fantasy"],
    moodProfile: { cozy: 0.9, magical: 0.6, lightFun: 0.6, emotional: 0.6 },
    approxPages: 420,
    popularity: 0.75,
  },
  {
    id: "atomic-habits",
    title: "Atomic Habits",
    author: "James Clear",
    genres: ["selfDevelopment", "nonFiction"],
    moodProfile: { thoughtProvoking: 0.9, lightFun: 0.2, cozy: 0.3 },
    approxPages: 320,
    popularity: 0.88,
  },
  {
    id: "song-of-achilles",
    title: "The Song of Achilles",
    author: "Madeline Miller",
    genres: ["historicalFiction", "romance"],
    moodProfile: { emotional: 0.95, intense: 0.5, escapist: 0.6, thoughtProvoking: 0.6 },
    approxPages: 380,
    popularity: 0.83,
  },
  {
    id: "gone-girl",
    title: "Gone Girl",
    author: "Gillian Flynn",
    genres: ["mysteryThriller"],
    moodProfile: { intense: 0.95, mysterious: 0.8, thoughtProvoking: 0.5 },
    approxPages: 420,
    popularity: 0.86,
  },
  {
    id: "educated",
    title: "Educated",
    author: "Tara Westover",
    genres: ["biography", "nonFiction"],
    moodProfile: { emotional: 0.8, thoughtProvoking: 0.9, intense: 0.5 },
    approxPages: 350,
    popularity: 0.79,
  },
  {
    id: "legends-and-lattes",
    title: "Legends & Lattes",
    author: "Travis Baldree",
    genres: ["fantasy", "youngAdult"],
    moodProfile: { cozy: 0.95, lightFun: 0.7, magical: 0.5, escapist: 0.6 },
    approxPages: 300,
    popularity: 0.7,
  },
];
